# action.yml
name: 'Run SDKMAN!'
description: 'Greet someone and record the time'
inputs:
  candidate:  # id of input
    description: 'Who to greet'
    required: true
  version: # id of input
    description: 'Who to greet'
    required: true
  platform: # id of input
    description: 'Who to greet'
    required: false
outputs:
  file: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.sdkman.outputs.file }}
runs:
  using: 'composite'
  steps:
    - id: sdkman
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.candidate }} ${{ inputs.version }} ${{ inputs.platform }}
      shell: bash
