# action.yml
name: 'Run SDKMAN!'
description: 'Download the sdk you want to install'
inputs:
  candidate:
    description: 'The name of the candidate to install'
    required: true
  version:
    description: 'The version of the candidate to install'
    required: true
outputs:
  file:
    description: 'Filename of the downloaded archive.'
    value: ${{ steps.sdkman.outputs.file }}
runs:
  using: 'composite'
  steps:
    - id: sdkman
      shell: bash
      run: |
        candidate=${{ inputs.candidate }}
        version=${{ inputs.version }}

        export SDKMAN_DIR="$HOME/.sdkman" && curl -s "https://get.sdkman.io?rcupdate=false" | bash
        source $HOME/.sdkman/bin/sdkman-init.sh && sdk install $candidate $version

        zip_output=$HOME/.sdkman/archives/$candidate-$version.zip
        echo "file=$zip_output" >> $GITHUB_OUTPUT
