name: Main workflow
on: [push, pull_request]

jobs:
  build:
    name: "JDK ${{ matrix.version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        version: [ 15.0.0.hs-adpt, 15.0.0.j9-adpt, 15.0.0-zulu, 15.0.0.fx-zulu, 15.0.0.fx-librca, 15.0.0-librca, 15-open, 15.0.0-sapmchn ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.version }}
      id: sdkman
      uses: ./
      with:
        candidate: java
        version: ${{ matrix.version }}
    - uses: actions/setup-java@v1
      id: setup-java
      with:
        java-version: 15
        jdkFile: ${{ steps.sdkman.outputs.file }}
    - name: Verify Java ${{ matrix.version }}
      run: java --version
