name: Main workflow
on: [push, pull_request]

jobs:
  build:
    name: "JDK ${{ matrix.version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        version: [ 17.0.0.35.1-amzn, 21.3.0.r17-grl, 17-open, 17.0.0.fx-librca, 17.0.0-librca, 17.0.0-ms, 17.0.0-oracle, 17-sapmchn, 17.0.0-tem, 17.0.0-zulu, 17.0.0.fx-zulu ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.version }}
      id: sdkman
      uses: ./
      with:
        candidate: java
        version: ${{ matrix.version }}
    - name: Verify Java ${{ matrix.version }}
      run: java -version
