name: Main workflow
on: [push, pull_request]

jobs:
  build:
    name: "JDK ${{ matrix.feature }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        candidate: [ java ]
        version: [ 11.0.2-open, 11.0.8-librca, 11.0.8-zulu, 11.0.8-amzn, 11.0.8.hs-adpt ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java 15.0.0-amzn
      uses: ./
      with:
        candidate: ${{ matrix.candidate }}
        version: ${{ matrix.version }}
    - uses: actions/setup-java@v1
      id: setup-java
      with:
        java-version: ${{ matrix.version }}
        jdkFile: ${{ github.workspace }}/.sdkman/archives/java-${{ matrix.version }}.zip
    - name: Verify Java 15.0.0-amzn
      run: test/verify-java.sh ${{ matrix.version }} "${{ steps.setup-java.outputs.path }}" "${{ steps.setup-java.outputs.version }}"
