name: Main workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: "JDK ${{ matrix.version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        version: [ 17.0.0.35.1-amzn, 21.3.0.r17-grl, 17-open, 17.0.0.fx-librca, 17.0.0-librca, 17.0.0-ms, 17.0.0-oracle, 17-sapmchn, 17.0.0-tem, 17.0.0-zulu, 17.0.0.fx-zulu ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java ${{ matrix.version }}
      id: sdkman
      uses: ./
      with:
        candidate: java
        version: ${{ matrix.version }}
    - uses: actions/setup-java@v3
      if: ${{ matrix.os == 'windows-latest' }}
      id: setup-java
      with:
        distribution: 'jdkfile'
        java-version: 17
        jdkFile: ${{ steps.sdkman.outputs.file }}
    - name: Verify Java ${{ matrix.version }}
      run: java -version
